# Generated by Django 5.1.2 on 2024-10-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='medicines/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Diabetic Care', 'Diabetic Care'), ('OTC Medicine', 'OTC Medicine'), ('Pain Relief', 'Pain Relief'), ('Vitamins & Supplements', 'Vitamins & Supplements'), ('Womens Care', 'Womens Care'), ('Cold & Flu', 'Cold & Flu'), ('Skin Care', 'Skin Care'), ('Others', 'Others')], max_length=50)),
                ('dosage_mg', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Capsule', 'Capsule'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Gel', 'Gel'), ('Others', 'Others')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
