# Generated by Django 5.1.6 on 2025-04-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_labtest_alter_appointment_patient_contact_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labbooking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='address',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='patient_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.CharField(choices=[('CBC', 'Complete blood count (CBC)'), ('ALT', 'Alanine transaminase (ALT)'), ('TSH', 'Thyroid stimulating hormone (TSH)'), ('TgAb', 'Thyroglobulin antibodies (TgAb)'), ('Glucose', 'Blood sugar (glucose) tests'), ('B12', 'Vitamin B12')], max_length=100, unique=True),
        ),
    ]
